/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:    ["var(--font-body)", "DM Sans", "sans-serif"],
        display: ["var(--font-display)", "Oswald", "sans-serif"],
        mono:    ["var(--font-mono)", "Space Mono", "monospace"],
      },
      colors: {
        tylon: {
          primary:   "#F0EDE6",
          secondary: "#141412",
          card:      "#1A1A17",
          border:    "#2A2A26",
          muted:     "#6B6B60",
          bg:        "#0D0D0B",
        },
        army: {
          DEFAULT: "#4A5C3A",
          light:   "#6B8050",
        },
        gold: {
          DEFAULT: "#8A7340",
          light:   "#B09860",
        },
        danger: { DEFAULT: "#6B2020" },
        // Keep for admin compat
        charcoal: {
          50:  "#F5F5F5",
          100: "#E8E8E8",
          200: "#C8C8C8",
          300: "#A0A0A0",
          400: "#707070",
          500: "#4A4A4A",
          600: "#333333",
          700: "#1F1F1F",
          800: "#141414",
          900: "#0A0A0A",
        },
        cream: {
          50:  "#FDFCFA",
          100: "#FAF7F4",
          200: "#F5EFE9",
          300: "#EDE4DB",
          400: "#E2D4C8",
        },
        stone: {
          50:  "#FAF9F8",
          100: "#F0EDEA",
          200: "#DDD8D2",
          300: "#C4BCAF",
          400: "#A49A8C",
          500: "#7D7168",
          600: "#5C524A",
          700: "#3D342E",
          800: "#2A2118",
          900: "#1A1310",
        },
        sage: {
          100: "#EAF0E8",
          200: "#C8D9C4",
          300: "#9BBD94",
          400: "#6B9E62",
          500: "#4A7A42",
          600: "#3A6033",
        },
        rose: {
          50:  "#FDF8F6",
          100: "#FAF0EC",
          200: "#F5E0D8",
          300: "#EDCABC",
          400: "#E0A898",
          500: "#CC7A68",
          600: "#B05A47",
        },
        border:     "hsl(var(--border-hsl))",
        input:      "hsl(var(--input))",
        ring:       "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
      },
      borderRadius: {
        "4xl": "2rem",
        "5xl": "2.5rem",
      },
      animation: {
        "fade-in":       "fadeIn 0.6s ease-out forwards",
        "slide-up":      "slideUp 0.5s ease-out forwards",
        "slide-in-right":"slideInRight 0.4s ease-out forwards",
        "scale-in":      "scaleIn 0.3s ease-out forwards",
        float:           "float 3s ease-in-out infinite",
        marquee:         "marquee 30s linear infinite",
        shimmer:         "shimmer 1.5s infinite",
        "pulse-slow":    "pulse 3s cubic-bezier(0.4,0,0.6,1) infinite",
      },
      keyframes: {
        fadeIn:       { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp:      { "0%": { transform: "translateY(30px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        slideInRight: { "0%": { transform: "translateX(100%)" }, "100%": { transform: "translateX(0)" } },
        scaleIn:      { "0%": { transform: "scale(0.95)", opacity: "0" }, "100%": { transform: "scale(1)", opacity: "1" } },
        float:        { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-8px)" } },
        marquee:      { "0%": { transform: "translateX(0%)" }, "100%": { transform: "translateX(-50%)" } },
        shimmer:      { "0%": { backgroundPosition: "-200px 0" }, "100%": { backgroundPosition: "calc(200px + 100%) 0" } },
      },
    },
  },
  plugins: [],
};
